# Jekyll Config File

theme                    : "minimal-mistakes-jekyll"
minimal_mistakes_skin    : "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# Site Settings
locale                   : "en-US"
title                    : "Abdullah Badawod"
title_separator          : "-"
subtitle                 : "Personal Website to showcase skills in Network Security"
name                     : "Abdullah Badawod"
description              : "Personal website showcasing my projects, certifications, and skills in Network Security and IT."
url                      : "https://abdullah-badawod.github.io"  # Update this with your live URL if available
baseurl                  : ""
repository               : "abdullah-badawod/github.io"
teaser                   : "/assets/images/500x300.png"
logo                     : "/assets/images/apple-touch-icon.png"
masthead_title           : "Abdullah's Professional Website"
words_per_minute         : 200

# Comments Section Configuration (Optional)
comments:
  provider               : false
  disqus:
    shortname            : 
  discourse:
    server               : 
  facebook:
    appid                :
    num_posts            : 5
    colorscheme          : "light"
  utterances:
    theme                : "github-light"
    issue_term           : "pathname"
  giscus:
    repo_id              :
    category_name        :
    category_id          :
    discussion_term      : "pathname"
    reactions_enabled    : 1
    theme                : "light"

# Social Sharing
twitter:
  username               : "abdullah_badawod"
facebook:
  username               : "abdullah.badawod"
og_image                 : "/assets/images/bio-photo.jpg"
social:
  type                   : "Person"
  name                   : "Abdullah Badawod"
  links: 
    - "https://twitter.com/abdullah_badawod"
    - "https://github.com/abdullah-badawod"
    - "https://www.linkedin.com/in/abdullah-badawod"
    - "https://instagram.com/abdullah.badawod"

# SEO and Google Analytics (optional)
google_site_verification : "YOUR_GOOGLE_VERIFICATION_CODE"
bing_site_verification   : "YOUR_BING_VERIFICATION_CODE"
yandex_site_verification : "YOUR_YANDEX_VERIFICATION_CODE"
analytics:
  provider               : "google"
  google:
    tracking_id          : "UA-XXXXXXX-X"

# Site Author Details
author:
  name             : "Abdullah Badawod"
  avatar           : "/assets/images/bio-photo.jpg"
  bio              : "Network Security Specialist with expertise in penetration testing, firewall configuration, and security assessments."
  location         : "Makkah and Jeddah, Saudi Arabia"
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/abdullah-badawod"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/abdullah-badawod"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/abdullah_badawod"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/abdullah.badawod"

# Certifications Section
certifications:
  - title: "Certified Network Security Professional"
    institution: "Security Academy"
    date: "2023"
  - title: "Certified Ethical Hacker"
    institution: "EC-Council"
    date: "2022"

# Free Courses Section
free_courses:
  - title: "Network Security Fundamentals"
    platform: "Coursera"
    date: "2022"
  - title: "Introduction to Firewall Management"
    platform: "Udemy"
    date: "2021"

# Footer Links
footer:
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/abdullah-badawod"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/abdullah-badawod"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter"
      url: "https://twitter.com/abdullah_badawod"

# Site Navigation and Pages
include:
  - .htaccess
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - Rakefile
  - README
  - tmp

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed

# Search Settings
search: true
search_full_content: true
search_provider: "lunr"
lunr:
  search_within_pages: true
algolia:
  application_id: "QB6HVGBSBA"
  index_name: "dev_minimal-mistakes"
  search_only_api_key: "9d5014e5bbc77372547bce778dfa5663"
  powered_by: true

# Output Settings
permalink: /:categories/:title/
paginate: 5
paginate_path: /page:num/
timezone: "Asia/Riyadh"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# Collections
collections:
  portfolio:
    output: true
    permalink: /:collection/:path/

# Defaults
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      share: true
      related: true
